// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFile():Promise<string>;

export function BrowseFolder():Promise<string>;

export function BrowseMultipleFiles():Promise<Array<string>>;

export function ExtractIcon(arg1:string):Promise<string>;

export function GetSystemTheme():Promise<string>;

export function LoadData():Promise<string>;

export function LoadSettings():Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function PasteClipboardFiles():Promise<Array<{name:string; path:string; type:string}>>;

export function ResolvePathType(arg1:string):Promise<string>;

export function SaveData(arg1:string):Promise<void>;

export function SaveSettings(arg1:string):Promise<void>;

export function SaveWindowSize():Promise<void>;
