// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseFile() {
  return window['go']['main']['App']['BrowseFile']();
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function BrowseMultipleFiles() {
  return window['go']['main']['App']['BrowseMultipleFiles']();
}

export function ExtractIcon(arg1) {
  return window['go']['main']['App']['ExtractIcon'](arg1);
}

export function FetchPageTitle(arg1) {
  return window['go']['main']['App']['FetchPageTitle'](arg1);
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function LoadData() {
  return window['go']['main']['App']['LoadData']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function PasteClipboardFiles() {
  return window['go']['main']['App']['PasteClipboardFiles']();
}

export function PasteClipboardImage() {
  return window['go']['main']['App']['PasteClipboardImage']();
}

export function ReadImageDataURI(arg1) {
  return window['go']['main']['App']['ReadImageDataURI'](arg1);
}

export function ResolvePathType(arg1) {
  return window['go']['main']['App']['ResolvePathType'](arg1);
}

export function SaveData(arg1) {
  return window['go']['main']['App']['SaveData'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWindowSize() {
  return window['go']['main']['App']['SaveWindowSize']();
}
